[feat] celery 연동하여 이미지 생성
TUK-DP/backend pull request #169
Opened 2024-08-01 11:21 UTC by rvbear

## PR type
- [ ] Bug fix
- [X] Feature
- [ ] Refactor
- [ ] Chore

## 💻 작업사항

- celery 연동하여 이미지 생성 작업하기
![pr](https://github.com/user-attachments/assets/e44e236d-7402-4835-ae4e-b153f4104885)

이미지 관련하여 호출할 api는 2개
POST image/generate는 기존에 우리가 사용했던 api와 동일합니다. 다만 달라진 내용은 이미지 url을 알려주지 않고 celery에게 작업을 맡긴 뒤 해당 taskId를 넘겨준다는 것 입니다. 

GET image/generate에서 taskId를 가지고 조회가 가능합니다. 이때 각 상태에 따라 다르게 값이 나오게 됩니다.

이렇게 변경을 하게 된 이유는 기존 api 한번 호출 시 오래 대기를 하는 경우가 있었는데, 이는 성능이나 사용감 측면에서 좋지 않기 때문입니다.
따라서 해당 요청을 비동기 처리 방식으로 변경하여 사용감 측면이나 성능적인 측면에서 효율을 높이기 위하여 변경하였습니다. 

<br>

- 변경된 API Docs

**POST image/generate**
request
```JSON
{
  "password": "string",
  "prompt": "string",
  "n": 3
}
```
response
```json
{
  "isSuccess": true,
  "message": "OK",
  "result": {
    "taskId": "12345678-1234-1234-1234-123456789123"
  }
}
```

**GET image/generate**
request
```
/image/generate?taskId=12345678-1234-1234-1234-123456789123
```
response 
PENDING일 때
```json
{
  "isSuccess": true,
  "message": "OK",
  "result": {
    "state": "PENDING",
    "status": "Task is pending"
  }
}
```

SUCCESS일 때
```json
{
  "isSuccess": true,
  "message": "OK",
  "result": {
    "state": "SUCCESS",
    "status": "Task completed",
    "result": [
      "imgurl",
      "imgurl",
      "imgurl"
    ]
  }
}
```

## 💡 작성한 이슈 외에 작업한 사항

- x

## ✔️ check list

- [X] 작성한 이슈의 내용을 전부 적용했나요?
- [X] 리뷰어를 등록했나요?

2024-08-01 13:12 UTC, Leewonchan14 requested changes
1. tasks.py 로 많은 함수를 옮겼는데
  이전에 사용하던 코드들이 잘동작하는지 확인 되었나요?
  
2. docker 컴포즈 prod 파일도 같이 수정해주세요

2024-08-01 13:12 UTC, Leewonchan14 commented on docker-compose-dev.yml
> +      - REDIS_URL=redis://redis:6379
현재 배포환경에서 8001번 포트는 다른 컨테이너가 사용중입니다.

인사이트에서 8001 번 포트가 필요한가요?

2024-08-01 13:13 UTC, Leewonchan14 commented
아 그리고 api 명세 정리도 여기 올려 주세요!

노션에 정리하셨으면 여기도 적어주시고 노션에도 적었다고 링크를 거시거나 한번 언급해 주시면 좋을것 같아요

2024-08-01 14:50 UTC, rvbear commented
기존 코드들은 잘 동작합니다!
api docs도 추가해두었고 추가 내용들도 확인하여 수정하였습니다!

2024-08-01 15:31 UTC, Leewonchan14 requested changes

2024-08-01 15:31 UTC, Leewonchan14 commented on docker-compose-prod.yml
> +
어 이건 수정 하면 안돼요 ㅋㅋ

2024-08-01 15:43 UTC, rvbear commented on docker-compose-prod.yml
> +
저거 원래 3305인가요..?

2024-08-01 15:57 UTC, Hj1218 approved these changes
수고하셨습니다!

2024-08-02 04:22 UTC, Leewonchan14 approved these changes

2024-08-02 06:16 UTC, merged